services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easyholmes-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_TOKEN=${API_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=easyholmes-database
      - DB_PORT=5432
      - DB_NAME=easyholmes
      - DB_USER=easyholmes
      - DB_PASSWORD=easyholmes123
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - easyholmes-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: easyholmes-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - easyholmes-network

  database:
    image: postgres:15-alpine
    container_name: easyholmes-database
    environment:
      - POSTGRES_DB=easyholmes
      - POSTGRES_USER=easyholmes
      - POSTGRES_PASSWORD=easyholmes123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - easyholmes-network

volumes:
  postgres_data:

networks:
  easyholmes-network:
    driver: bridge 