services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easyholmes-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_TOKEN=${API_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - easyholmes-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: easyholmes-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - easyholmes-network

  database:
    image: alpine:latest
    container_name: easyholmes-database
    volumes:
      - sqlite_data:/data
    networks:
      - easyholmes-network

volumes:
  sqlite_data:

networks:
  easyholmes-network:
    driver: bridge 